/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "common.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(Player, Player, AUTO)


PB_BIND(Vehicle, Vehicle, AUTO)


PB_BIND(SensorBatteryReading, SensorBatteryReading, AUTO)


PB_BIND(SensorDistanceReading, SensorDistanceReading, AUTO)


PB_BIND(SensorContactReading, SensorContactReading, AUTO)


PB_BIND(SensorPositionReading, SensorPositionReading, AUTO)


PB_BIND(SensorReading, SensorReading, AUTO)


PB_BIND(CameraFrame, CameraFrame, AUTO)


PB_BIND(MotorStateMessage, MotorStateMessage, AUTO)


PB_BIND(PingRequest, PingRequest, AUTO)


PB_BIND(PingResponse, PingResponse, AUTO)





















