/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_PLAYER_PLAYER_PB_H_INCLUDED
#define PB_PLAYER_PLAYER_PB_H_INCLUDED
#include <pb.h>
#include "common.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _player_MoveControlType {
    player_MoveControlType_MOVE_CONTROL_UNKNOWN = 0,
    player_MoveControlType_MOVE_CONTROL_FORWARD = 1,
    player_MoveControlType_MOVE_CONTROL_BACKWARD = 2,
    player_MoveControlType_MOVE_CONTROL_FORWARD_LEFT = 3,
    player_MoveControlType_MOVE_CONTROL_FORWARD_RIGHT = 4,
    player_MoveControlType_MOVE_CONTROL_BACKWARD_LEFT = 5,
    player_MoveControlType_MOVE_CONTROL_BACKWARD_RIGHT = 6,
    player_MoveControlType_MOVE_CONTROL_TURN_LEFT = 7,
    player_MoveControlType_MOVE_CONTROL_TURN_RIGHT = 8
} player_MoveControlType;

/* Struct definitions */
typedef struct _player_JoinRequest {
    pb_callback_t token;
    pb_callback_t name;
    pb_callback_t location;
} player_JoinRequest;

typedef struct _player_JoinResponse {
    uint32_t assigned_id;
    PlayerRole assigned_role;
} player_JoinResponse;

typedef struct _player_JoinBroadcast {
    bool has_player;
    Player player;
    uint64_t timestamp;
} player_JoinBroadcast;

typedef struct _player_LeaveBroadcast {
    pb_callback_t player_id;
    uint64_t timestamp;
} player_LeaveBroadcast;

typedef struct _player_ListPlayerRequest {
    PlayerRole role;
    pb_callback_t name;
    pb_callback_t location;
    uint32_t page;
    uint32_t limit;
} player_ListPlayerRequest;

typedef struct _player_ListPlayerResponse {
    pb_callback_t players;
    uint32_t total;
    uint32_t page;
    uint32_t limit;
    uint32_t next_page;
    uint32_t prev_page;
} player_ListPlayerResponse;

typedef struct _player_ChatRequest {
    pb_callback_t message;
} player_ChatRequest;

typedef struct _player_ChatResponse {
    ErrorCode error;
} player_ChatResponse;

typedef struct _player_ChatBroadcast {
    pb_callback_t player_id;
    pb_callback_t message;
    uint64_t timestamp;
} player_ChatBroadcast;

typedef struct _player_ListVehiclesRequest {
    VehicleType type;
    pb_callback_t name;
    pb_callback_t location;
    pb_callback_t tag;
    bool acquired;
    uint32_t page;
    uint32_t limit;
} player_ListVehiclesRequest;

typedef struct _player_ListVehiclesResponse {
    pb_callback_t vehicles;
    uint32_t total;
    uint32_t page;
    uint32_t limit;
    uint32_t next_page;
    uint32_t prev_page;
    ErrorCode error;
} player_ListVehiclesResponse;

typedef struct _player_VehicleConnectedBroadcast {
    bool has_vehicle;
    Vehicle vehicle;
    uint64_t timestamp;
} player_VehicleConnectedBroadcast;

typedef struct _player_VehicleDisconnectedBroadcast {
    pb_callback_t vehicle_id;
    uint64_t timestamp;
} player_VehicleDisconnectedBroadcast;

typedef struct _player_AcquireRequest {
    pb_callback_t vehicle_id;
} player_AcquireRequest;

typedef struct _player_AcquireResponse {
    pb_callback_t vehicle_id;
    bool success;
    ErrorCode error;
} player_AcquireResponse;

typedef struct _player_AcquireBroadcast {
    pb_callback_t vehicle_id;
    bool has_player;
    Player player;
} player_AcquireBroadcast;

typedef struct _player_MoveControlRequest {
    pb_callback_t vehicle_id;
    player_MoveControlType type;
} player_MoveControlRequest;

typedef struct _player_MoveControlResponse {
    pb_callback_t motors;
    ErrorCode error;
} player_MoveControlResponse;

typedef struct _player_VehicleCameraBroadcast {
    pb_callback_t vehicle_id;
    uint64_t timestamp;
    bool has_frame;
    CameraFrame frame;
} player_VehicleCameraBroadcast;

typedef struct _player_VehicleStateBroadcast {
    pb_callback_t vehicle_id;
    uint64_t timestamp;
    pb_callback_t sensors;
    pb_callback_t motors;
} player_VehicleStateBroadcast;

typedef struct _player_ReleaseRequest {
    pb_callback_t vehicle_id;
} player_ReleaseRequest;

typedef struct _player_ReleaseResponse {
    pb_callback_t vehicle_id;
    ErrorCode error;
} player_ReleaseResponse;

typedef struct _player_ReleaseBroadcast {
    pb_callback_t vehicle_id;
    bool has_player;
    Player player;
} player_ReleaseBroadcast;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _player_MoveControlType_MIN player_MoveControlType_MOVE_CONTROL_UNKNOWN
#define _player_MoveControlType_MAX player_MoveControlType_MOVE_CONTROL_TURN_RIGHT
#define _player_MoveControlType_ARRAYSIZE ((player_MoveControlType)(player_MoveControlType_MOVE_CONTROL_TURN_RIGHT+1))


#define player_JoinResponse_assigned_role_ENUMTYPE PlayerRole



#define player_ListPlayerRequest_role_ENUMTYPE PlayerRole



#define player_ChatResponse_error_ENUMTYPE ErrorCode


#define player_ListVehiclesRequest_type_ENUMTYPE VehicleType

#define player_ListVehiclesResponse_error_ENUMTYPE ErrorCode




#define player_AcquireResponse_error_ENUMTYPE ErrorCode


#define player_MoveControlRequest_type_ENUMTYPE player_MoveControlType

#define player_MoveControlResponse_error_ENUMTYPE ErrorCode




#define player_ReleaseResponse_error_ENUMTYPE ErrorCode



/* Initializer values for message structs */
#define player_JoinRequest_init_default          {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define player_JoinResponse_init_default         {0, _PlayerRole_MIN}
#define player_JoinBroadcast_init_default        {false, Player_init_default, 0}
#define player_LeaveBroadcast_init_default       {{{NULL}, NULL}, 0}
#define player_ListPlayerRequest_init_default    {_PlayerRole_MIN, {{NULL}, NULL}, {{NULL}, NULL}, 0, 0}
#define player_ListPlayerResponse_init_default   {{{NULL}, NULL}, 0, 0, 0, 0, 0}
#define player_ChatRequest_init_default          {{{NULL}, NULL}}
#define player_ChatResponse_init_default         {_ErrorCode_MIN}
#define player_ChatBroadcast_init_default        {{{NULL}, NULL}, {{NULL}, NULL}, 0}
#define player_ListVehiclesRequest_init_default  {_VehicleType_MIN, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, 0, 0, 0}
#define player_ListVehiclesResponse_init_default {{{NULL}, NULL}, 0, 0, 0, 0, 0, _ErrorCode_MIN}
#define player_VehicleConnectedBroadcast_init_default {false, Vehicle_init_default, 0}
#define player_VehicleDisconnectedBroadcast_init_default {{{NULL}, NULL}, 0}
#define player_AcquireRequest_init_default       {{{NULL}, NULL}}
#define player_AcquireResponse_init_default      {{{NULL}, NULL}, 0, _ErrorCode_MIN}
#define player_AcquireBroadcast_init_default     {{{NULL}, NULL}, false, Player_init_default}
#define player_MoveControlRequest_init_default   {{{NULL}, NULL}, _player_MoveControlType_MIN}
#define player_MoveControlResponse_init_default  {{{NULL}, NULL}, _ErrorCode_MIN}
#define player_VehicleCameraBroadcast_init_default {{{NULL}, NULL}, 0, false, CameraFrame_init_default}
#define player_VehicleStateBroadcast_init_default {{{NULL}, NULL}, 0, {{NULL}, NULL}, {{NULL}, NULL}}
#define player_ReleaseRequest_init_default       {{{NULL}, NULL}}
#define player_ReleaseResponse_init_default      {{{NULL}, NULL}, _ErrorCode_MIN}
#define player_ReleaseBroadcast_init_default     {{{NULL}, NULL}, false, Player_init_default}
#define player_JoinRequest_init_zero             {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define player_JoinResponse_init_zero            {0, _PlayerRole_MIN}
#define player_JoinBroadcast_init_zero           {false, Player_init_zero, 0}
#define player_LeaveBroadcast_init_zero          {{{NULL}, NULL}, 0}
#define player_ListPlayerRequest_init_zero       {_PlayerRole_MIN, {{NULL}, NULL}, {{NULL}, NULL}, 0, 0}
#define player_ListPlayerResponse_init_zero      {{{NULL}, NULL}, 0, 0, 0, 0, 0}
#define player_ChatRequest_init_zero             {{{NULL}, NULL}}
#define player_ChatResponse_init_zero            {_ErrorCode_MIN}
#define player_ChatBroadcast_init_zero           {{{NULL}, NULL}, {{NULL}, NULL}, 0}
#define player_ListVehiclesRequest_init_zero     {_VehicleType_MIN, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, 0, 0, 0}
#define player_ListVehiclesResponse_init_zero    {{{NULL}, NULL}, 0, 0, 0, 0, 0, _ErrorCode_MIN}
#define player_VehicleConnectedBroadcast_init_zero {false, Vehicle_init_zero, 0}
#define player_VehicleDisconnectedBroadcast_init_zero {{{NULL}, NULL}, 0}
#define player_AcquireRequest_init_zero          {{{NULL}, NULL}}
#define player_AcquireResponse_init_zero         {{{NULL}, NULL}, 0, _ErrorCode_MIN}
#define player_AcquireBroadcast_init_zero        {{{NULL}, NULL}, false, Player_init_zero}
#define player_MoveControlRequest_init_zero      {{{NULL}, NULL}, _player_MoveControlType_MIN}
#define player_MoveControlResponse_init_zero     {{{NULL}, NULL}, _ErrorCode_MIN}
#define player_VehicleCameraBroadcast_init_zero  {{{NULL}, NULL}, 0, false, CameraFrame_init_zero}
#define player_VehicleStateBroadcast_init_zero   {{{NULL}, NULL}, 0, {{NULL}, NULL}, {{NULL}, NULL}}
#define player_ReleaseRequest_init_zero          {{{NULL}, NULL}}
#define player_ReleaseResponse_init_zero         {{{NULL}, NULL}, _ErrorCode_MIN}
#define player_ReleaseBroadcast_init_zero        {{{NULL}, NULL}, false, Player_init_zero}

/* Field tags (for use in manual encoding/decoding) */
#define player_JoinRequest_token_tag             1
#define player_JoinRequest_name_tag              2
#define player_JoinRequest_location_tag          3
#define player_JoinResponse_assigned_id_tag      1
#define player_JoinResponse_assigned_role_tag    2
#define player_JoinBroadcast_player_tag          1
#define player_JoinBroadcast_timestamp_tag       2
#define player_LeaveBroadcast_player_id_tag      1
#define player_LeaveBroadcast_timestamp_tag      2
#define player_ListPlayerRequest_role_tag        1
#define player_ListPlayerRequest_name_tag        2
#define player_ListPlayerRequest_location_tag    3
#define player_ListPlayerRequest_page_tag        4
#define player_ListPlayerRequest_limit_tag       5
#define player_ListPlayerResponse_players_tag    1
#define player_ListPlayerResponse_total_tag      2
#define player_ListPlayerResponse_page_tag       3
#define player_ListPlayerResponse_limit_tag      4
#define player_ListPlayerResponse_next_page_tag  5
#define player_ListPlayerResponse_prev_page_tag  6
#define player_ChatRequest_message_tag           1
#define player_ChatResponse_error_tag            1
#define player_ChatBroadcast_player_id_tag       1
#define player_ChatBroadcast_message_tag         2
#define player_ChatBroadcast_timestamp_tag       3
#define player_ListVehiclesRequest_type_tag      1
#define player_ListVehiclesRequest_name_tag      2
#define player_ListVehiclesRequest_location_tag  3
#define player_ListVehiclesRequest_tag_tag       4
#define player_ListVehiclesRequest_acquired_tag  5
#define player_ListVehiclesRequest_page_tag      6
#define player_ListVehiclesRequest_limit_tag     7
#define player_ListVehiclesResponse_vehicles_tag 1
#define player_ListVehiclesResponse_total_tag    2
#define player_ListVehiclesResponse_page_tag     3
#define player_ListVehiclesResponse_limit_tag    4
#define player_ListVehiclesResponse_next_page_tag 5
#define player_ListVehiclesResponse_prev_page_tag 6
#define player_ListVehiclesResponse_error_tag    7
#define player_VehicleConnectedBroadcast_vehicle_tag 1
#define player_VehicleConnectedBroadcast_timestamp_tag 2
#define player_VehicleDisconnectedBroadcast_vehicle_id_tag 1
#define player_VehicleDisconnectedBroadcast_timestamp_tag 2
#define player_AcquireRequest_vehicle_id_tag     1
#define player_AcquireResponse_vehicle_id_tag    1
#define player_AcquireResponse_success_tag       2
#define player_AcquireResponse_error_tag         3
#define player_AcquireBroadcast_vehicle_id_tag   1
#define player_AcquireBroadcast_player_tag       2
#define player_MoveControlRequest_vehicle_id_tag 1
#define player_MoveControlRequest_type_tag       2
#define player_MoveControlResponse_motors_tag    1
#define player_MoveControlResponse_error_tag     2
#define player_VehicleCameraBroadcast_vehicle_id_tag 1
#define player_VehicleCameraBroadcast_timestamp_tag 2
#define player_VehicleCameraBroadcast_frame_tag  3
#define player_VehicleStateBroadcast_vehicle_id_tag 1
#define player_VehicleStateBroadcast_timestamp_tag 2
#define player_VehicleStateBroadcast_sensors_tag 3
#define player_VehicleStateBroadcast_motors_tag  4
#define player_ReleaseRequest_vehicle_id_tag     1
#define player_ReleaseResponse_vehicle_id_tag    1
#define player_ReleaseResponse_error_tag         2
#define player_ReleaseBroadcast_vehicle_id_tag   1
#define player_ReleaseBroadcast_player_tag       2

/* Struct field encoding specification for nanopb */
#define player_JoinRequest_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   token,             1) \
X(a, CALLBACK, SINGULAR, STRING,   name,              2) \
X(a, CALLBACK, SINGULAR, STRING,   location,          3)
#define player_JoinRequest_CALLBACK pb_default_field_callback
#define player_JoinRequest_DEFAULT NULL

#define player_JoinResponse_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   assigned_id,       1) \
X(a, STATIC,   SINGULAR, UENUM,    assigned_role,     2)
#define player_JoinResponse_CALLBACK NULL
#define player_JoinResponse_DEFAULT NULL

#define player_JoinBroadcast_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  player,            1) \
X(a, STATIC,   SINGULAR, UINT64,   timestamp,         2)
#define player_JoinBroadcast_CALLBACK NULL
#define player_JoinBroadcast_DEFAULT NULL
#define player_JoinBroadcast_player_MSGTYPE Player

#define player_LeaveBroadcast_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   player_id,         1) \
X(a, STATIC,   SINGULAR, UINT64,   timestamp,         2)
#define player_LeaveBroadcast_CALLBACK pb_default_field_callback
#define player_LeaveBroadcast_DEFAULT NULL

#define player_ListPlayerRequest_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    role,              1) \
X(a, CALLBACK, SINGULAR, STRING,   name,              2) \
X(a, CALLBACK, SINGULAR, STRING,   location,          3) \
X(a, STATIC,   SINGULAR, UINT32,   page,              4) \
X(a, STATIC,   SINGULAR, UINT32,   limit,             5)
#define player_ListPlayerRequest_CALLBACK pb_default_field_callback
#define player_ListPlayerRequest_DEFAULT NULL

#define player_ListPlayerResponse_FIELDLIST(X, a) \
X(a, CALLBACK, REPEATED, MESSAGE,  players,           1) \
X(a, STATIC,   SINGULAR, UINT32,   total,             2) \
X(a, STATIC,   SINGULAR, UINT32,   page,              3) \
X(a, STATIC,   SINGULAR, UINT32,   limit,             4) \
X(a, STATIC,   SINGULAR, UINT32,   next_page,         5) \
X(a, STATIC,   SINGULAR, UINT32,   prev_page,         6)
#define player_ListPlayerResponse_CALLBACK pb_default_field_callback
#define player_ListPlayerResponse_DEFAULT NULL
#define player_ListPlayerResponse_players_MSGTYPE Player

#define player_ChatRequest_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   message,           1)
#define player_ChatRequest_CALLBACK pb_default_field_callback
#define player_ChatRequest_DEFAULT NULL

#define player_ChatResponse_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    error,             1)
#define player_ChatResponse_CALLBACK NULL
#define player_ChatResponse_DEFAULT NULL

#define player_ChatBroadcast_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   player_id,         1) \
X(a, CALLBACK, SINGULAR, STRING,   message,           2) \
X(a, STATIC,   SINGULAR, UINT64,   timestamp,         3)
#define player_ChatBroadcast_CALLBACK pb_default_field_callback
#define player_ChatBroadcast_DEFAULT NULL

#define player_ListVehiclesRequest_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    type,              1) \
X(a, CALLBACK, SINGULAR, STRING,   name,              2) \
X(a, CALLBACK, SINGULAR, STRING,   location,          3) \
X(a, CALLBACK, SINGULAR, STRING,   tag,               4) \
X(a, STATIC,   SINGULAR, BOOL,     acquired,          5) \
X(a, STATIC,   SINGULAR, UINT32,   page,              6) \
X(a, STATIC,   SINGULAR, UINT32,   limit,             7)
#define player_ListVehiclesRequest_CALLBACK pb_default_field_callback
#define player_ListVehiclesRequest_DEFAULT NULL

#define player_ListVehiclesResponse_FIELDLIST(X, a) \
X(a, CALLBACK, REPEATED, MESSAGE,  vehicles,          1) \
X(a, STATIC,   SINGULAR, UINT32,   total,             2) \
X(a, STATIC,   SINGULAR, UINT32,   page,              3) \
X(a, STATIC,   SINGULAR, UINT32,   limit,             4) \
X(a, STATIC,   SINGULAR, UINT32,   next_page,         5) \
X(a, STATIC,   SINGULAR, UINT32,   prev_page,         6) \
X(a, STATIC,   SINGULAR, UENUM,    error,             7)
#define player_ListVehiclesResponse_CALLBACK pb_default_field_callback
#define player_ListVehiclesResponse_DEFAULT NULL
#define player_ListVehiclesResponse_vehicles_MSGTYPE Vehicle

#define player_VehicleConnectedBroadcast_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  vehicle,           1) \
X(a, STATIC,   SINGULAR, UINT64,   timestamp,         2)
#define player_VehicleConnectedBroadcast_CALLBACK NULL
#define player_VehicleConnectedBroadcast_DEFAULT NULL
#define player_VehicleConnectedBroadcast_vehicle_MSGTYPE Vehicle

#define player_VehicleDisconnectedBroadcast_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   vehicle_id,        1) \
X(a, STATIC,   SINGULAR, UINT64,   timestamp,         2)
#define player_VehicleDisconnectedBroadcast_CALLBACK pb_default_field_callback
#define player_VehicleDisconnectedBroadcast_DEFAULT NULL

#define player_AcquireRequest_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   vehicle_id,        1)
#define player_AcquireRequest_CALLBACK pb_default_field_callback
#define player_AcquireRequest_DEFAULT NULL

#define player_AcquireResponse_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   vehicle_id,        1) \
X(a, STATIC,   SINGULAR, BOOL,     success,           2) \
X(a, STATIC,   SINGULAR, UENUM,    error,             3)
#define player_AcquireResponse_CALLBACK pb_default_field_callback
#define player_AcquireResponse_DEFAULT NULL

#define player_AcquireBroadcast_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   vehicle_id,        1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  player,            2)
#define player_AcquireBroadcast_CALLBACK pb_default_field_callback
#define player_AcquireBroadcast_DEFAULT NULL
#define player_AcquireBroadcast_player_MSGTYPE Player

#define player_MoveControlRequest_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   vehicle_id,        1) \
X(a, STATIC,   SINGULAR, UENUM,    type,              2)
#define player_MoveControlRequest_CALLBACK pb_default_field_callback
#define player_MoveControlRequest_DEFAULT NULL

#define player_MoveControlResponse_FIELDLIST(X, a) \
X(a, CALLBACK, REPEATED, MESSAGE,  motors,            1) \
X(a, STATIC,   SINGULAR, UENUM,    error,             2)
#define player_MoveControlResponse_CALLBACK pb_default_field_callback
#define player_MoveControlResponse_DEFAULT NULL
#define player_MoveControlResponse_motors_MSGTYPE MotorStateMessage

#define player_VehicleCameraBroadcast_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   vehicle_id,        1) \
X(a, STATIC,   SINGULAR, UINT64,   timestamp,         2) \
X(a, STATIC,   OPTIONAL, MESSAGE,  frame,             3)
#define player_VehicleCameraBroadcast_CALLBACK pb_default_field_callback
#define player_VehicleCameraBroadcast_DEFAULT NULL
#define player_VehicleCameraBroadcast_frame_MSGTYPE CameraFrame

#define player_VehicleStateBroadcast_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   vehicle_id,        1) \
X(a, STATIC,   SINGULAR, UINT64,   timestamp,         2) \
X(a, CALLBACK, REPEATED, MESSAGE,  sensors,           3) \
X(a, CALLBACK, REPEATED, MESSAGE,  motors,            4)
#define player_VehicleStateBroadcast_CALLBACK pb_default_field_callback
#define player_VehicleStateBroadcast_DEFAULT NULL
#define player_VehicleStateBroadcast_sensors_MSGTYPE SensorReading
#define player_VehicleStateBroadcast_motors_MSGTYPE MotorStateMessage

#define player_ReleaseRequest_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   vehicle_id,        1)
#define player_ReleaseRequest_CALLBACK pb_default_field_callback
#define player_ReleaseRequest_DEFAULT NULL

#define player_ReleaseResponse_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   vehicle_id,        1) \
X(a, STATIC,   SINGULAR, UENUM,    error,             2)
#define player_ReleaseResponse_CALLBACK pb_default_field_callback
#define player_ReleaseResponse_DEFAULT NULL

#define player_ReleaseBroadcast_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   vehicle_id,        1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  player,            2)
#define player_ReleaseBroadcast_CALLBACK pb_default_field_callback
#define player_ReleaseBroadcast_DEFAULT NULL
#define player_ReleaseBroadcast_player_MSGTYPE Player

extern const pb_msgdesc_t player_JoinRequest_msg;
extern const pb_msgdesc_t player_JoinResponse_msg;
extern const pb_msgdesc_t player_JoinBroadcast_msg;
extern const pb_msgdesc_t player_LeaveBroadcast_msg;
extern const pb_msgdesc_t player_ListPlayerRequest_msg;
extern const pb_msgdesc_t player_ListPlayerResponse_msg;
extern const pb_msgdesc_t player_ChatRequest_msg;
extern const pb_msgdesc_t player_ChatResponse_msg;
extern const pb_msgdesc_t player_ChatBroadcast_msg;
extern const pb_msgdesc_t player_ListVehiclesRequest_msg;
extern const pb_msgdesc_t player_ListVehiclesResponse_msg;
extern const pb_msgdesc_t player_VehicleConnectedBroadcast_msg;
extern const pb_msgdesc_t player_VehicleDisconnectedBroadcast_msg;
extern const pb_msgdesc_t player_AcquireRequest_msg;
extern const pb_msgdesc_t player_AcquireResponse_msg;
extern const pb_msgdesc_t player_AcquireBroadcast_msg;
extern const pb_msgdesc_t player_MoveControlRequest_msg;
extern const pb_msgdesc_t player_MoveControlResponse_msg;
extern const pb_msgdesc_t player_VehicleCameraBroadcast_msg;
extern const pb_msgdesc_t player_VehicleStateBroadcast_msg;
extern const pb_msgdesc_t player_ReleaseRequest_msg;
extern const pb_msgdesc_t player_ReleaseResponse_msg;
extern const pb_msgdesc_t player_ReleaseBroadcast_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define player_JoinRequest_fields &player_JoinRequest_msg
#define player_JoinResponse_fields &player_JoinResponse_msg
#define player_JoinBroadcast_fields &player_JoinBroadcast_msg
#define player_LeaveBroadcast_fields &player_LeaveBroadcast_msg
#define player_ListPlayerRequest_fields &player_ListPlayerRequest_msg
#define player_ListPlayerResponse_fields &player_ListPlayerResponse_msg
#define player_ChatRequest_fields &player_ChatRequest_msg
#define player_ChatResponse_fields &player_ChatResponse_msg
#define player_ChatBroadcast_fields &player_ChatBroadcast_msg
#define player_ListVehiclesRequest_fields &player_ListVehiclesRequest_msg
#define player_ListVehiclesResponse_fields &player_ListVehiclesResponse_msg
#define player_VehicleConnectedBroadcast_fields &player_VehicleConnectedBroadcast_msg
#define player_VehicleDisconnectedBroadcast_fields &player_VehicleDisconnectedBroadcast_msg
#define player_AcquireRequest_fields &player_AcquireRequest_msg
#define player_AcquireResponse_fields &player_AcquireResponse_msg
#define player_AcquireBroadcast_fields &player_AcquireBroadcast_msg
#define player_MoveControlRequest_fields &player_MoveControlRequest_msg
#define player_MoveControlResponse_fields &player_MoveControlResponse_msg
#define player_VehicleCameraBroadcast_fields &player_VehicleCameraBroadcast_msg
#define player_VehicleStateBroadcast_fields &player_VehicleStateBroadcast_msg
#define player_ReleaseRequest_fields &player_ReleaseRequest_msg
#define player_ReleaseResponse_fields &player_ReleaseResponse_msg
#define player_ReleaseBroadcast_fields &player_ReleaseBroadcast_msg

/* Maximum encoded size of messages (where known) */
/* player_JoinRequest_size depends on runtime parameters */
/* player_LeaveBroadcast_size depends on runtime parameters */
/* player_ListPlayerRequest_size depends on runtime parameters */
/* player_ListPlayerResponse_size depends on runtime parameters */
/* player_ChatRequest_size depends on runtime parameters */
/* player_ChatBroadcast_size depends on runtime parameters */
/* player_ListVehiclesRequest_size depends on runtime parameters */
/* player_ListVehiclesResponse_size depends on runtime parameters */
/* player_VehicleDisconnectedBroadcast_size depends on runtime parameters */
/* player_AcquireRequest_size depends on runtime parameters */
/* player_AcquireResponse_size depends on runtime parameters */
/* player_AcquireBroadcast_size depends on runtime parameters */
/* player_MoveControlRequest_size depends on runtime parameters */
/* player_MoveControlResponse_size depends on runtime parameters */
/* player_VehicleCameraBroadcast_size depends on runtime parameters */
/* player_VehicleStateBroadcast_size depends on runtime parameters */
/* player_ReleaseRequest_size depends on runtime parameters */
/* player_ReleaseResponse_size depends on runtime parameters */
/* player_ReleaseBroadcast_size depends on runtime parameters */
#define player_ChatResponse_size                 2
#define player_JoinResponse_size                 8
#if defined(Player_size)
#define PLAYER_PLAYER_PB_H_MAX_SIZE              player_JoinBroadcast_size
#define player_JoinBroadcast_size                (17 + Player_size)
#endif
#if defined(Vehicle_size)
#define player_VehicleConnectedBroadcast_size    (17 + Vehicle_size)
#endif

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
