/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "vehicle.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(vehicle_Capabalities, vehicle_Capabalities, AUTO)


PB_BIND(vehicle_JoinRequest, vehicle_JoinRequest, AUTO)


PB_BIND(vehicle_JoinResponse, vehicle_JoinResponse, AUTO)


PB_BIND(vehicle_SensorRequest, vehicle_SensorRequest, AUTO)


PB_BIND(vehicle_SensorResponse, vehicle_SensorResponse, AUTO)


PB_BIND(vehicle_AcquireRequest, vehicle_AcquireRequest, AUTO)


PB_BIND(vehicle_AcquireResponse, vehicle_AcquireResponse, AUTO)


PB_BIND(vehicle_ReleaseRequest, vehicle_ReleaseRequest, AUTO)


PB_BIND(vehicle_ReleaseResponse, vehicle_ReleaseResponse, AUTO)


PB_BIND(vehicle_CameraSnapRequest, vehicle_CameraSnapRequest, AUTO)


PB_BIND(vehicle_CameraSnapResponse, vehicle_CameraSnapResponse, AUTO)


PB_BIND(vehicle_CameraStateRequest, vehicle_CameraStateRequest, AUTO)


PB_BIND(vehicle_CameraStateResponse, vehicle_CameraStateResponse, AUTO)


PB_BIND(vehicle_MotorStateRequest, vehicle_MotorStateRequest, AUTO)


PB_BIND(vehicle_MotorStateResponse, vehicle_MotorStateResponse, AUTO)


PB_BIND(vehicle_Envelope, vehicle_Envelope, AUTO)



