
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - USERNAME=${USERNAME:-nobody}
        - USER_UID=${USER_UID:-1000}
        - USER_GID=${USER_GID:-1000}
    tty: true
