
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - USERNAME=${USERNAME:-devcontainer}
        - USER_UID=${USER_UID:-2000}
        - USER_GID=${USER_GID:-2000}
    volumes:
      - ~/.gitconfig:/home/${USERNAME}/.gitconfig:ro
      - ~/.ssh:/home/${USERNAME}/.ssh:ro
      - ~/.npmrc:/home/${USERNAME}/.npmrc:ro
    command: bash -c "while true; do sleep 3; done"
