
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - USERNAME=${USERNAME:-devcontainer}
        - USER_UID=${USER_UID:-2000}
        - USER_GID=${USER_GID:-2000}
    tty: true
