name: Build Documentation

permissions:
  contents: write
  id-token: write

on:
  push:
    branches:
      - master  # Change this if your default branch has a different name
    paths:
      - 'docs/**/*.puml'  # Only run when PlantUML files change
  
  # Allow manual triggering of the workflow
  workflow_dispatch:
    inputs:
      reason:
        description: 'Reason for manual trigger'
        required: false
        default: 'Manual documentation build'

jobs:
  build-and-push-docs:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history for proper branch creation
      
      - name: Config
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
      
      - name: Install PlantUML
        run: |
          sudo apt-get update
          sudo apt-get install -y plantuml
      
      - name: Branch
        run: |
          git fetch origin docs || echo "No remote docs branch yet"
          if git show-ref --quiet refs/heads/docs; then
            git checkout docs
          else
            git checkout -b docs
          fi
      
      - name: Build
        run: |
          for puml_file in docs/*.puml; do
            base_name=$(basename "$puml_file" .puml)
            echo "Converting $base_name to PNG..."
            plantuml -tpng -o . "$puml_file"
          done
      
      - name: Commit
        run: |
          git add docs/
          git commit -m "Update docs from ${{ github.sha }}" || echo "No changes to commit"

      - name: Push
        run: |
          git subtree split --prefix=docs -b temp-docs-branch
          git push --force origin temp-docs-branch:docs
