name: Publish CI Image


permissions:
  contents: read
  packages: write
  id-token: write


on:
  push:
    branches:
      - master
    paths:
      - '.devcontainer/**'
  
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Login
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin

      - name: Publish
        uses: devcontainers/ci@v0.3
        with:
          imageName: ghcr.io/project-ore0/proto-ci
          cacheFrom: ghcr.io/project-ore0/proto-ci
          push: always
