name: Publish TypeScript Package


permissions:
  contents: write
  packages: write
  id-token: write


on:
  create:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Login
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Generate
        uses: devcontainers/ci@v0.3
        with:
          cacheFrom: ghcr.io/project-ore0/proto-ci
          push: never
          runCmd: make
      
      - name: Version
        id: version
        run: |
          # Determine version from tag
          if [[ "${GITHUB_REF}" == refs/tags/v* ]]; then
            # Extract version from tag
            version="${GITHUB_REF#refs/tags/v}"
            echo "version=${version}" >> $GITHUB_OUTPUT
          else
            echo 'No tag found to determine version' >&2
            exit 1
          fi

      - name: Bundle C
        run: |
          tar -czf "generated/project-ore0-proto-c-${{ steps.version.outputs.version }}.tgz" -C generated/c .
      
      - name: Bundle TypeScript
        run: |
          cd generated/ts
          # Create package.json
          cat > package.json << EOF
          {
            "name": "@project-ore0/proto-ts",
            "version": "${{ steps.version.outputs.version }}",
            "description": "Generated TypeScript types for Project Ore0 Protocol Buffers",
            "main": "index.ts",
            "types": "index.ts",
            "repository": {
              "type": "git",
              "url": "git+https://github.com/project-ore0/proto.git"
            },
            "dependencies": {
              "google-protobuf": "^3.21.4"
            },
            "author": "Project Ore0",
            "license": "MIT"
          }
          EOF
          # Pack as tgz
          npm pack --pack-destination ..
      
      - name: Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: project-ore0-proto-${{ steps.version.outputs.version }}
          path: |
            generated/c/*
            generated/ts/*

      - name: Release
        uses: softprops/action-gh-release@v2
        if: github.ref_type == 'tag'
        with:
          files: |
            generated/project-ore0-proto-c-${{ steps.version.outputs.version }}.tgz
            generated/project-ore0-proto-ts-${{ steps.version.outputs.version }}.tgz
